title: CoolPenguin27's Website
description: Its his website.
url: "https://coolpenguin27.github.io/"
remote_theme: daviddarnes/garth

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
